site_name: "Chaitin Tech"
docs_dir: "../../docs/en"
site_dir: "../../generated/en"
site_url: https://t1k.chaitin.com/en/

copyright: Copyright &copy; 2024 Chaitin Tech

theme:
  name: material
  custom_dir: "../../overrides/"
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  language: en
  palette:
    - scheme: slate
      primary: black
      accent: indigo
  features:
    - content.tooltips
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra_css:
  - assets/stylesheets/extra.css

extra:
  generator: false
  alternate:
    - name: EN
      link: /en/
      lang: en
    - name: 中文
      link: /zh/
      lang: zh

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Documentation: docs.md
  - Official Website: https://www.chaitin.cn/en
